-- 1. Nomes das categorias que possuam preços entre R$ 100,00 e R$ 200,00.
SELECT NOME FROM CATEGORIA C WHERE C.VALOR_DIA BETWEEN 100 AND 200;
SELECT NOME FROM CATEGORIA C WHERE C.VALOR_DIA >= 100 AND C.VALOR_DIA <= 200;

-- 2. Nomes das categorias cujos nomes possuam a palavra ‘Luxo’.
SELECT NOME FROM CATEGORIA WHERE NOME ILIKE '%Luxo%';
SELECT NOME FROM CATEGORIA C WHERE C.NOME ILIKE '%Luxo%';

-- 3. Número dos apartamentos que estão ocupados, ou seja, a data de saída está vazia.
SELECT DISTINCT A.NUM FROM APARTAMENTO A, HOSPEDAGEM HO WHERE A.NUM = HO.NUM AND DT_SAI IS NULL;
SELECT DISTINCT A.NUM FROM APARTAMENTO A JOIN HOSPEDAGEM HO ON A.NUM = HO.NUM AND DT_SAI IS NULL;

-- 4. Número dos apartamentos cuja categoria tenha código 1, 2, 3, 11, 34, 54, 24, 12.
SELECT NUM FROM APARTAMENTO A, CATEGORIA C WHERE A.COD_CAT = C.COD_CAT AND C.COD_CAT IN (1, 2, 3, 11, 34, 54, 24, 12);
SELECT NUM FROM APARTAMENTO A JOIN CATEGORIA C ON A.COD_CAT = C.COD_CAT AND C.COD_CAT IN (1, 2, 3, 11, 34, 54, 24, 12);

-- 5. Todas as informações dos apartamentos cujas categorias iniciam com a palavra ‘Luxo’.
SELECT * FROM APARTAMENTO WHERE COD_CAT IN (SELECT COD_CAT FROM CATEGORIA WHERE NOME ILIKE 'Luxo%');

-- 6. Quantidade de apartamentos cadastrados no sistema.
SELECT COUNT(*) AS QUANTIDADE_APTO FROM APARTAMENTO;

-- 7. Somatório dos preços das categorias.
SELECT SUM(VALOR_DIA) AS SOMATORIO_PRECOS FROM CATEGORIA;

-- 8. Média de preços das categorias.
SELECT AVG(VALOR_DIA) AS MEDIA_PRECOS FROM CATEGORIA;

-- 9. Maior preço de categoria.
SELECT MAX(VALOR_DIA) AS MAIOR_PRECO FROM CATEGORIA;

-- 10. Menor preço de categoria.
SELECT MIN(VALOR_DIA) AS MENOR_PRECO FROM CATEGORIA;

-- 11. Nome dos hóspedes que nasceram após 1° de janeiro de 1970.
SELECT NOME FROM HOSPEDE WHERE DT_NASC > '1970-01-01';

-- 12. Quantidade de hóspedes.
SELECT COUNT(*) AS QUANTIDADE_HOSPEDES FROM HOSPEDE;

-- 13. Altere a tabela Hóspede, acrescentando o campo "Nacionalidade".

-- DELETAR COLUNA
ALTER TABLE HOSPEDE DROP COLUMN NACIONALIDADE;

-- ADICIONAR COLUNA
ALTER TABLE HOSPEDE ADD COLUMN NACIONALIDADE VARCHAR(30);

-- 14. A data de nascimento do hóspede mais velho.
SELECT DT_NASC FROM HOSPEDE WHERE DT_NASC IN (SELECT MIN(DT_NASC) FROM HOSPEDE);

-- 15. A data de nascimento do hóspede mais novo.
SELECT DT_NASC FROM HOSPEDE WHERE DT_NASC IN (SELECT MAX(DT_NASC) FROM HOSPEDE);

-- 16. O nome do hóspede mais velho
SELECT NOME FROM HOSPEDE WHERE DT_NASC IN (SELECT MIN(DT_NASC) FROM HOSPEDE);
 
-- 17. Reajuste em 10% o valor das diárias das categorias.
UPDATE CATEGORIA SET VALOR_DIA = VALOR_DIA * 1.10;

-- 18. O número do apartamento mais caro ocupado pelo João.
SELECT A.NUM FROM APARTAMENTO A, HOSPEDAGEM HO, HOSPEDE H WHERE A.NUM = HO.NUM AND HO.COD_HOSP = H.COD_HOSP AND H.NOME ILIKE
'João' AND A.COD_CAT IN (SELECT COD_CAT FROM CATEGORIA WHERE VALOR_DIA IN (SELECT MAX(VALOR_DIA) FROM CATEGORIA));

SELECT A.NUM FROM APARTAMENTO A JOIN HOSPEDAGEM HO ON A.NUM = HO.NUM JOIN HOSPEDE H ON HO.COD_HOSP = H.COD_HOSP AND H.NOME 
ILIKE 'João' AND A.COD_CAT IN (SELECT COD_CAT FROM CATEGORIA WHERE VALOR_DIA IN (SELECT MAX(VALOR_DIA) FROM CATEGORIA));

-- 19. O nome dos hóspedes que nunca se hospedaram no apartamento 201.
SELECT NOME FROM HOSPEDE H LEFT JOIN HOSPEDAGEM HO ON H.COD_HOSP = HO.COD_HOSP AND HO.NUM = 201
GROUP BY NOME HAVING COUNT(HO.NUM) = 0;

-- 20. O nome dos hóspedes que nunca se hospedaram em apartamentos da categoria LUXO.
-- TODOS - SE HOSPEDARAM NA CATEGORIA LUXO
SELECT NOME FROM HOSPEDE H, HOSPEDAGEM HO, APARTAMENTO A WHERE H.COD_HOSP = HO.COD_HOSP AND HO.NUM = A.NUM
EXCEPT
SELECT NOME FROM HOSPEDE H, HOSPEDAGEM HO, APARTAMENTO A WHERE H.COD_HOSP = HO.COD_HOSP AND HO.NUM = A.NUM AND A.COD_CAT IN
(SELECT COD_CAT FROM CATEGORIA WHERE NOME ILIKE 'LUXO');

-- 21. O nome do hóspede mais velho que foi atendido pelo atendente mais novo.
SELECT H.NOME FROM HOSPEDE H, HOSPEDAGEM HO, FUNCIONARIO F WHERE H.COD_HOSP = HO.COD_HOSP AND HO.COD_FUNC = F.COD_FUNC AND
H.DT_NASC IN (SELECT MIN(DT_NASC) FROM HOSPEDE) AND F.DT_NASC IN (SELECT MAX(DT_NASC) FROM FUNCIONARIO);

SELECT H.NOME FROM HOSPEDE H JOIN HOSPEDAGEM HO ON H.COD_HOSP = HO.COD_HOSP JOIN FUNCIONARIO F ON HO.COD_FUNC = F.COD_FUNC 
WHERE H.DT_NASC IN (SELECT MIN(DT_NASC) FROM HOSPEDE) AND F.DT_NASC IN (SELECT MAX(DT_NASC) FROM FUNCIONARIO);

-- 22. O nome da categoria mais cara que foi ocupado pelo hóspede mais velho.
SELECT C.NOME FROM CATEGORIA C, HOSPEDAGEM HO, APARTAMENTO A, HOSPEDE H WHERE H.COD_HOSP = HO.COD_HOSP AND A.NUM = HO.NUM AND
C.COD_CAT = A.COD_CAT AND H.DT_NASC IN (SELECT MIN(DT_NASC) FROM HOSPEDE) AND C.VALOR_DIA IN (SELECT MAX(VALOR_DIA) FROM
CATEGORIA);